export const SWITCH_USER = 'SWITCH_USER';
export const SUBMIT_ACTION = 'SUBMIT_ACTION';
export const INPUT_CHANGE_OUTSIDE = 'INPUT_CHANGE_OUTSIDE';
export const INPUT_CHANGE_INSIDE = 'INPUT_CHANGE_INSIDE';
export const MASK = 'MASK';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const SHOW_HIDE = 'SHOW_HIDE';